# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        IMAGE_BASE: ${IMAGE_BASE:-hapnan/base-image:cuda-12.5.1-base-24.04}
      tags:
        - "hapnan/linux-desktop:${IMAGE_TAG:-cuda-12.5.1-base-24.04}"
        
    image: hapnan/linux-desktop:${IMAGE_TAG:-cuda-12.5.1-base-24.04}
    
    shm_size: 2G
    
    ## For Nvidia GPU's - You probably want to uncomment this
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    devices:
      - "/dev/dri:/dev/dri"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
    
    volumes:
      - ./config/rclone:/etc/rclone
      # Workspace
      - ./workspace:${WORKSPACE:-/workspace}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/ai-dock/bin/provisioning.sh
    
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST:-2222}:${SSH_PORT_LOCAL:-22}
        # Web UI for easy service access
        - ${SERVICEPORTAL_PORT_HOST:-1111}:${SERVICEPORTAL_PORT_HOST:-1111}
        # Coturn
        - ${COTURN_PORT_HOST:-3478}:${COTURN_PORT_HOST:-3478}
        # Selkies
        - ${WEBRTC_PORT_HOST:-6100}:${WEBRTC_PORT_HOST:-6100}
        # VNC
        - ${VNC_PORT_HOST:-6200}:${VNC_PORT_HOST:-6200}
        # Syncthing
        - ${SYNCTHING_UI_PORT_HOST:-8384}:${SYNCTHING_UI_PORT_HOST:-8384}
        - ${SYNCTHING_TRANSPORT_PORT_HOST:-22999}:${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
        - 8080:8080/udp
        - 8181:8181/tcp
        - 4455:4455/tcp

    environment:
        # Don't enclose values in quotes
        - ENABLE_COTURN=${ENABLE_COTURN:-false}
        # External IP
        - COTURN_LISTEN_ADDRESS=${COTURN_LISTEN_ADDRESS:-127.0.0.1}
        - COTURN_PORT_HOST=${COTURN_PORT_HOST:-3478}
        - COTURN_USER=${COTURN_USER:-user}
        # Auto-generated when empty
        - COTURN_PASSWORD=${COTURN_PASSWORD:-}
        # External IP if coturn
        - TURN_HOST=${TURN_HOST:-127.0.0.1}
        - TURN_PORT=${TURN_PORT:-3478}
        - TURN_PROTOCOL=${TURN_PROTOCOL:-tcp}
        - TURN_USERNAME=${TURN_USERNAME:-}
        - TURN_PASSWORD=${TURN_PASSWORD:-}
        - WEBRTC_ENABLE_RESIZE=${WEBRTC_ENABLE_RESIZE:-false}
        - WEBRTC_ENCODER=${WEBRTC_ENCODER:-nvh264enc}
        - WEBRTC_FLAGS=${WEBRTC_FLAGS:-}
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-true}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-password}
        - SSH_PORT_HOST=${SSH_PORT_HOST:-2222}
        - SSH_PORT_LOCAL=${SSH_PORT_LOCAL:-22}
        - SERVICEPORTAL_PORT_HOST=${SERVICEPORTAL_PORT_HOST:-1111}
        - SERVICEPORTAL_METRICS_PORT=${SERVICEPORTAL_METRICS_PORT:-21111}
        - SERVICEPORTAL_URL=${SERVICEPORTAL_URL:-}
        - VNC_PORT_HOST=${VNC_PORT_HOST:-6200}
        - VNC_METRICS_PORT=${VNC_METRICS_PORT:-26200}
        - VNC_URL=${VNC_URL:-}
        - WEBRTC_PORT_HOST=${WEBRTC_PORT_HOST:-6100}
        - WEBRTC_METRICS_PORT=${WEBRTC_METRICS_PORT:-26100}
        - WEBRTC_URL=${WEBRTC_URL:-}
        - SERVERLESS=${SERVERLESS:-false}
        - SYNCTHING_UI_PORT_HOST=${SYNCTHING_UI_PORT_HOST:-8384}
        - SYNCTHING_TRANSPORT_PORT_HOST=${SYNCTHING_TRANSPORT_PORT_HOST:-22999}
        - SYNCTHING_URL=${SYNCTHING_URL:-}
        #- PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT:-}
        
    # Magic bullet to solve networking issues - I don't like it
    # Turn server works fine both within local network and for internet
    #network_mode: "host"
